---

- hosts: localhost
  connection: local
  become: true

  vars:
    system_packages:
     - tmux
     - htop

  tasks:
    - name: Install system packages
      package:
        name: "{{ system_packages }}"
